<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>AvorionAdmin.Agent</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\AvorionAdmin.Core\AvorionAdmin.Core.csproj" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="8.0.30" />
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
</Project>
